version: '3.4'

services:

  nanomq:
    container_name: nanomq
    image: emqx/nanomq
    ports:
      - 1883:1883
    networks:
      - mqtt
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_etc:/etc/grafana
      - grafana_var_lib:/var/lib/grafana
    networks:
      - grafana
    restart: always

  ticktock:
    container_name: database
    image: vilisseranen/ticktock
    networks:
      - grafana
      - data
    volumes:
      - ticktock:/var/lib/ticktock
    restart: always

  data-logger:
    container_name: data-logger
    image: vilisseranen/temperature-server
    depends_on:
      - ticktock
      - nanomq
    environment:
      - BROKER=tcp://nanomq:1883
    networks:
      - mqtt
      - data
    restart: always

networks:
  mqtt:
  grafana:
  data:
volumes:
  ticktock:
  grafana_etc:
  grafana_var_lib:
