version: '3.4'

services:
  nanomq:
    container_name: nanomq
    image: emqx/nanomq
    ports:
      - 1883:1883
    networks:
      - mqtt
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    ports:
      - 3000:3000
    volumes:
      - database:/data
      - grafana_etc:/etc/grafana
      - grafana_var_lib:/var/lib/grafana
    restart: always
  sqlite-logger:
    container_name: sqlite-logger
    image: vilisseranen/temperature-server
    environment:
      - BROKER=tcp://nanomq:1883
    volumes:
      - database:/data
    networks:
      - mqtt
    restart: always

networks:
  mqtt:
volumes:
  database:
  grafana_etc:
  grafana_var_lib:
